version: "3.9"
services:
  process-cpr:
    build: .
    container_name: process-cpr-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8092:8092"
    network_mode: "host"
